# Generated by Django 4.1.5 on 2023-05-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0012_user_groups_alter_company_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
            ],
            options={
                'db_table': 'generic_skills',
                'default_permissions': (),
                'unique_together': {('name', 'type', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Pseudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verticals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('identity', models.CharField(blank=True, max_length=250, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('portfolio', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('show_summary', models.BooleanField(default=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pseudo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.pseudos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('repo', models.CharField(blank=True, max_length=500, null=True)),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.CharField(max_length=500)),
                ('platform', models.CharField(max_length=250)),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('institute', models.CharField(blank=True, max_length=250, null=True)),
                ('degree', models.CharField(blank=True, max_length=250, null=True)),
                ('grade', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('template', models.TextField()),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('link', models.TextField(blank=True, null=True)),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('generic_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.genericskills')),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pseudos.verticals')),
            ],
            options={
                'db_table': 'skills',
                'default_permissions': (),
                'unique_together': {('vertical', 'generic_skill')},
            },
        ),
    ]
