# Generated by Django 4.1.5 on 2023-06-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_regions_tools_alter_candidatecompany_unique_together_and_more'),
        ('pseudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalsRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.regions')),
                ('verticals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
