# Generated by Django 3.2.20 on 2023-07-25 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0017_userregions'),
        ('pseudos', '0002_verticalsregions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('template_key', models.CharField(blank=True, max_length=250, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertical_config_user', to=settings.AUTH_USER_MODEL)),
                ('user_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertical_config_team', to='authentication.team')),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertical_config', to='pseudos.verticals')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
