# Generated by Django 3.2.20 on 2023-07-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0003_verticalconfigurations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verticalconfigurations',
            old_name='user_team',
            new_name='team',
        ),
    ]
