# Generated by Django 4.1.5 on 2023-05-15 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0013_profile_vertical_team_verticals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pseudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_status', models.IntegerField(choices=[(0, 'To Apply'), (1, 'Applied'), (2, 'Hired'), (3, 'Rejected'), (4, 'Cold Lead'), (5, 'Warm Lead'), (6, 'Hot Lead'), (7, 'Prospect')], default=0)),
                ('resume', models.TextField(blank=True, null=True)),
                ('is_manual_resume', models.BooleanField(default=False)),
                ('cover_letter', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applied_job_status',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BlacklistJobs',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=2000)),
                ('company_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('job_source', models.CharField(max_length=2000)),
                ('job_type', models.CharField(blank=True, max_length=2000, null=True)),
                ('address', models.CharField(max_length=2000)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('tech_keywords', models.TextField(blank=True, null=True)),
                ('job_posted_date', models.DateTimeField(blank=True, null=True)),
                ('job_source_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('block', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'job_detail',
                'ordering': ['-job_posted_date'],
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='jobdetail',
            index=models.Index(fields=['company_name', 'job_source', 'tech_keywords', 'job_posted_date'], name='job_detail_company_6736d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobdetail',
            unique_together={('company_name', 'job_title')},
        ),
        migrations.AlterIndexTogether(
            name='jobdetail',
            index_together={('company_name', 'job_title')},
        ),
        migrations.AddField(
            model_name='blacklistjobs',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
        migrations.AddField(
            model_name='appliedjobstatus',
            name='applied_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='applied by'),
        ),
        migrations.AddField(
            model_name='appliedjobstatus',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal.jobdetail'),
        ),
        migrations.AddField(
            model_name='appliedjobstatus',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.team'),
        ),
        migrations.AddField(
            model_name='appliedjobstatus',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pseudos.verticals'),
        ),
    ]
