# Generated by Django 4.1.5 on 2023-05-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobstatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliedjobstatus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
