# Generated by Django 4.1.5 on 2023-05-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_appliedjobstatus_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjobstatus',
            old_name='deleted_at',
            new_name='converted_at',
        ),
        migrations.RenameField(
            model_name='appliedjobstatus',
            old_name='is_deleted',
            new_name='is_converted',
        ),
    ]
