# Generated by Django 4.1.5 on 2023-05-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_rename_deleted_at_appliedjobstatus_converted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEngineJobsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('jobs_count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
