# Generated by Django 4.1.5 on 2023-06-06 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_salesenginejobsstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobArchive',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=2000)),
                ('company_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('job_source', models.CharField(max_length=2000)),
                ('job_type', models.CharField(blank=True, max_length=2000, null=True)),
                ('address', models.CharField(max_length=2000)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('tech_keywords', models.TextField(blank=True, null=True)),
                ('job_posted_date', models.DateTimeField(blank=True, null=True)),
                ('job_source_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('block', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'job_archive',
                'ordering': ['-job_posted_date'],
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='jobarchive',
            index=models.Index(fields=['company_name', 'job_source', 'tech_keywords', 'job_posted_date'], name='job_archive_company_0e85ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobarchive',
            unique_together={('company_name', 'job_title')},
        ),
        migrations.AlterIndexTogether(
            name='jobarchive',
            index_together={('company_name', 'job_title')},
        ),
    ]
