# Generated by Django 4.1.5 on 2023-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0005_jobarchive_jobarchive_job_archive_company_0e85ea_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobUploadLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
