# Generated by Django 4.1.5 on 2023-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0006_jobuploadlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobuploadlogs',
            name='total',
        ),
        migrations.AddField(
            model_name='jobuploadlogs',
            name='jobs_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
