# Generated by Django 4.1.5 on 2023-06-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0007_remove_jobuploadlogs_total_jobuploadlogs_jobs_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobarchive',
            unique_together=set(),
        ),
    ]
