# Generated by Django 3.2.20 on 2023-07-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0013_salesenginejobsstats_job_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='job_description_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
