# Generated by Django 3.2.20 on 2023-08-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0016_auto_20230815_1321'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobarchive',
            name='job_archive_job_sou_50203f_idx',
        ),
        migrations.AddIndex(
            model_name='jobarchive',
            index=models.Index(fields=['job_type', 'job_posted_date', 'tech_keywords', 'job_type'], name='job_archive_job_typ_d873bc_idx'),
        ),
    ]
