# Generated by Django 3.2.20 on 2023-08-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0017_auto_20230816_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job_type', models.CharField(max_length=50)),
                ('jobs', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
