# Generated by Django 3.2.20 on 2023-08-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0018_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='job_posted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
