# Generated by Django 3.2.20 on 2023-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0019_analytics_job_posted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('contract_on_site', models.IntegerField(default=0)),
                ('contract_remote', models.IntegerField(default=0)),
                ('full_time_on_site', models.IntegerField(default=0)),
                ('full_time_remote', models.IntegerField(default=0)),
                ('hybrid_full_time', models.IntegerField(default=0)),
                ('hybrid_contract', models.IntegerField(default=0)),
                ('job_posted_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
