# Generated by Django 4.1.5 on 2023-08-25 11:08

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20230811_1848'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_portal', '0020_techstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('instance_id', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=200)),
                ('changes', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'edit_history',
                'default_permissions': (),
                'unique_together': {('instance_id', 'model', 'changes', 'user')},
            },
        ),
    ]
