# Generated by Django 4.1.5 on 2023-08-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0021_jobdetail_edited_edithistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edithistory',
            unique_together=set(),
        ),
    ]
