# Generated by Django 4.1.5 on 2023-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0024_downloadlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlogs',
            name='query',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
