# Generated by Django 4.1.5 on 2023-09-18 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0025_downloadlogs_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='tech_stacks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
    ]
