# Generated by Django 4.1.5 on 2023-10-23 15:29

from django.db import migrations, models
import job_portal.utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0027_restrictvertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesenginejobsstats',
            name='source',
            field=models.CharField(default=job_portal.utils.helpers.SalesEngineLogsNaming['PRODUCTION_TO_SALES_ENGINE'], max_length=250),
        ),
        migrations.AddField(
            model_name='salesenginejobsstats',
            name='upload_status',
            field=models.BooleanField(default=True),
        ),
    ]
