# Generated by Django 4.1.5 on 2023-11-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0029_alter_salesenginejobsstats_jobs_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesenginejobsstats',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesenginejobsstats',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
