# Generated by Django 4.1.5 on 2023-05-16 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_portal', '0001_initial'),
        ('authentication', '0013_profile_vertical_team_verticals'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.company')),
            ],
            options={
                'db_table': 'company_status',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_job_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_portal.appliedjobstatus')),
                ('company_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_management.companystatus')),
            ],
            options={
                'db_table': 'lead',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('effect_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('company_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_management.companystatus')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_management.lead')),
            ],
            options={
                'db_table': 'lead_activity',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'status',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_management.companystatus')),
            ],
            options={
                'db_table': 'phase',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LeadActivityNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('lead_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_management.leadactivity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_activity_notes',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_management.phase'),
        ),
        migrations.AddField(
            model_name='lead',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_management.phase'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companystatus',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_management.status'),
        ),
        migrations.AlterUniqueTogether(
            name='leadactivity',
            unique_together={('lead', 'company_status', 'phase')},
        ),
        migrations.AlterUniqueTogether(
            name='companystatus',
            unique_together={('company', 'status')},
        ),
    ]
