# Generated by Django 4.1.5 on 2023-05-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
        ('lead_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
        migrations.AlterField(
            model_name='lead',
            name='applied_job_status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_portal.appliedjobstatus'),
        ),
    ]
