# Generated by Django 3.2.20 on 2023-07-25 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead_management', '0004_alter_leadactivity_unique_together_lead_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
