# Generated by Django 4.1.5 on 2023-03-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_dashboard', 'view dashboard'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
