# Generated by Django 4.1.5 on 2023-03-03 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAPIIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, choices=[('chat gpt', 'Chat GPT'), ('github', 'Github'), ('google', 'Google')], max_length=250, null=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
            ],
            options={
                'db_table': 'company_api_integration',
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='CompanyIntegration',
        ),
    ]
