# Generated by Django 4.1.5 on 2023-03-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_companyapiintegration_delete_companyintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
