# Generated by Django 4.1.5 on 2023-03-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='reporting',
            new_name='reporting_to',
        ),
    ]
