# Generated by Django 4.1.5 on 2023-03-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_reporting_team_reporting_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyUser',
        ),
    ]
