# Generated by Django 4.1.5 on 2023-03-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
        migrations.AddField(
            model_name='profile',
            name='file_url',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
