# Generated by Django 4.1.5 on 2023-03-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_profile_file_profile_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
