# Generated by Django 4.1.5 on 2023-03-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_profile_file_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
    ]
