# Generated by Django 4.1.5 on 2023-03-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_role_company'),
        ('authentication', '0009_alter_profile_unique_together'),
    ]

    operations = [
    ]
