# Generated by Django 4.1.5 on 2023-03-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_merge_20230310_1616'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('company', 'employee_id')},
        ),
    ]
