# Generated by Django 4.1.5 on 2023-04-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0001_initial'),
        ('authentication', '0012_user_groups_alter_company_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vertical',
            field=models.ManyToManyField(blank=True, related_name='vertical', to='pseudos.verticals'),
        ),
        migrations.AddField(
            model_name='team',
            name='verticals',
            field=models.ManyToManyField(blank=True, related_name='verticals', to='pseudos.verticals'),
        ),
    ]
