# Generated by Django 4.1.5 on 2023-05-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_profile_vertical_team_verticals'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='custompermission',
            unique_together={('module', 'codename', 'name')},
        ),
    ]
