# Generated by Django 4.1.5 on 2023-05-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_custompermission_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'ordering': ('module',)},
        ),
    ]
