# Generated by Django 3.2.20 on 2023-08-11 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pseudos', '0004_rename_user_team_verticalconfigurations_team'),
        ('authentication', '0017_userregions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='codename',
            field=models.CharField(default='nothing', max_length=200),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='level',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='module',
            field=models.CharField(default='nothing', max_length=200),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='name',
            field=models.CharField(default='nothing', max_length=200),
        ),
        migrations.CreateModel(
            name='TeamRoleVerticalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_verticals', to='authentication.role')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='authentication.team')),
                ('vertical', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_role_vertical', to='pseudos.verticals')),
            ],
            options={
                'unique_together': {('role', 'member', 'team', 'vertical')},
            },
        ),
        migrations.CreateModel(
            name='MultipleRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('role', 'user')},
            },
        ),
    ]
