# Generated by Django 4.1.5 on 2023-09-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20230811_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompermission',
            name='child',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='parent',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
