# Generated by Django 4.1.5 on 2023-06-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupScraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='week_days',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.CreateModel(
            name='GroupScraperQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('queries', models.JSONField()),
                ('group_scraper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.groupscraper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='groupscraper',
            name='scheduler_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.schedulersettings'),
        ),
    ]
