# Generated by Django 4.1.5 on 2023-06-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_groupscraper_schedulersettings_is_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperlogs',
            name='filename',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='scraperlogs',
            name='uploaded_jobs',
            field=models.IntegerField(default=0),
        ),
    ]
