# Generated by Django 4.1.5 on 2023-06-23 10:27

from django.db import migrations, models
import settings.utils.model_fields.email


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scraperlogs_filename_scraperlogs_uploaded_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', settings.utils.model_fields.email.LowercaseEmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
