# Generated by Django 3.2.20 on 2023-08-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersync',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulersync',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
