# Generated by Django 4.1.5 on 2023-09-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_remove_groupscraperquery_queries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersync',
            name='uploading',
            field=models.BooleanField(default=False),
        ),
    ]
