# Generated by Django 4.1.5 on 2023-10-26 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_restrictedjobstags_groupscraper_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Source should contain only alphabetic or numeric characters (no spaces or special characters).', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='accounts',
            unique_together={('email', 'source')},
        ),
    ]
