# Generated by Django 4.1.5 on 2023-12-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_accounts_source_alter_accounts_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupscraper',
            name='is_analytics',
            field=models.BooleanField(default=False),
        ),
    ]
