# Generated by Django 4.1.5 on 2024-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_groupscraper_is_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupscraper',
            name='running_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupscraperquery',
            name='preference',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
