# Generated by Django 4.1.5 on 2023-05-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_email_alter_candidate_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
