# Generated by Django 4.1.5 on 2023-05-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_custompermission_options'),
        ('candidate', '0005_alter_exposedcandidate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('company', 'title')},
        ),
    ]
