# Generated by Django 4.1.5 on 2023-05-02 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('log_message', models.TextField(null=True)),
                ('error_message', models.TextField(null=True)),
                ('error_line', models.TextField(null=True)),
                ('traceback', models.TextField(null=True)),
                ('path', models.CharField(max_length=1000, null=True)),
                ('line_number', models.IntegerField(null=True)),
                ('method', models.CharField(max_length=10, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
